services:
  mysql:
    image: mysql:8.4
    container_name: hankki-atti-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hankki_atti_db
      MYSQL_USER: hankki
      MYSQL_PASSWORD: hankki
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
